### PR TITLE
Fix error handling when task cannot be created

### PR DESCRIPTION
**Pull request by djmitche**
Fixes:
```
ReferenceError: err is not defined
  File "/app/routes/v1.js", line 416, in Object.callee$0$0$
    error: "could not create task: " + err.toString()
```

@hammad13060 - r?

### CODE REVIEW

**Comment by hammad13060** [comment]
Seems right to me, but why didn't we catch this error [here](https://github.com/hammad13060/taskcluster-hooks/blob/6d74c77169389c693d17077b66efdb042ef0c31b/test/api_test.js#L261) earlier.

Does this have to do something with the node version ??

**Comment by djmitche** [comment]
I bet it's this line:
```
 (err) => { debug("Got expected authentication error: %s", err); });
```
in fact that error is *not* expected -- we should get the 400 that the lines above assert.

**Comment by djmitche** [comment]
(The error that line is logging about is the ReferenceError!)

**Comment by djmitche** [comment]
Actually, it's worse than that -- the triggerHook call itself returns InvalidScopes (rather than the createTask call it makes returning that error).

**Comment by djmitche** [comment]
OK, test case updated too.  That got a little more complicated than I expected!

**Comment by hammad13060** [comment]
this test checks for the proper reply if task trigger is not successful. Probably we will need another test which  checks for invalid scopes.

**Comment by djmitche** [comment]
Oh, good point -- the name is wrong.  If hook.task had invalid scopes, we'd get this error -- or if it caused an error for some other reason.

Calling triggerTask with incorrect scopes isn't that interesting, since taskcluster-lib-api takes care of checking that.  So it's not something we need to test in hooks.

**Comment by djmitche** [comment]
test name updated.

**Comment by hammad13060** [comment]
Hmm, now this test looks good :)

**Pull request closed without merging**
