### PR TITLE
Passing two new options to app

### PR DESCRIPTION
**Pull request by yash-iiith**

### CODE REVIEW

**Comment by yash-iiith** [comment]
@djmitche

**Comment by djmitche** [comment]
Also: a good commit message might be:

```
Enable a docs link at the root URL

Taskcluster-lib-app now supports generating a link to the documentation,
and requires the `docs` object to do so, so pass that to its constructor.
```

**Comment by petemoore** [comment]
@yash-iiith Was this intentionally closed, or did you mean to merge it? Many thanks!

**Comment by djmitche** [comment]
It was fixed in #57

**Pull request closed without merging**
