### PR TITLE
Use tc-lib-docs

### PR DESCRIPTION
**Pull request by djmitche**
This is based on #36.  I'm interested to see what Travis does with it, since there's no change to `npm-shrinkwrap.json`.  Have I shared with you my feelings about npm?

### CODE REVIEW

**Comment by djmitche** [comment]
Oh, hey, Travis isn't set up, go figure.

**Comment by djmitche** [comment]
good thing we closed https://bugzilla.mozilla.org/show_bug.cgi?id=1219313

**Comment by djmitche** [comment]
OK, this is frustrating :(

**Comment by djmitche** [comment]
OK, @imbstack plz rescue me from Node hell!

I've upgraded my dev machine and Travis to Node 6, which is what is running in Heroku.  I've tried two things that should have worked:

Run `rm -rf node_modules && npm install` with the package.json/npm-shrinkwrap.json from master, then run `npm install --save taskcluster-lib-docs@^3.3.0`.  The result is a change to package.json with no change to npm-shrinkwrap.json (which does not contain the string "taskcluster-lib-docs").  And predictably, this fails to run in Travis.

I then switched this to yarn by removing npm-shrinkwrap.json and running `rm -rf node_modules && yarn` based on a package.json containing taskcluster-lib-docs.  This produced a yarn.lock, which I checked in and pushed.  Travis barfed with:
```
Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/taskcluster/taskcluster-hooks/node_modules/buffertools/buffertools.js:26:20)
```
although it runs fine for me.  I removed node_modules and re-ran yarn on my desktop machine (slightly different version of node 6, I think), and it produced a bunch of diffs to yarn.lock.  I checked that in, pushed, and the same thing.

**Comment by djmitche** [comment]
Hm, #39 deleted `npm-shrinkwrap.json`.  @jonasfj was that intentional?

**Comment by jonasfj** [comment]
@djmitche, nope that was not intentional... @imbstack and I upgraded all pulse libraries yesterday... I guess one slipped :)

**Comment by djmitche** [comment]
Well, let's leave it of for a minute until I can get this landed :)

**Comment by djmitche** [comment]
Even without `npm-shrinkwrap.json`, node 6 failed to install bufferutil.  I'm trying with node 7 now.

**Comment by djmitche** [comment]
Still no love.  The Travis caches are cleared.  What variable am I missing here?

**Comment by jonasfj** [comment]
I think you just need to cargo cult a bit in the travis file:
```yml
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
```
From taskcluster-queue... Basically we need to upgrade gcc.

**Comment by djmitche** [comment]
Thank you!

**Comment by djmitche** [comment]
OMG OMG OMG GREEN ;)

**Comment by djmitche** [comment]
I'm un-assigning the review since this is based on #36 on which I need to make some revisions.

**Comment by djmitche** [comment]
OK, #36 has landed, so this is ready for review.

**Pull request merged**
